package Vistas;

import Modelos.FacturaVenta;
import Modelos.FacturaVentaModelo;
import Modelos.DetalleVenta;
import Modelos.DetalleVentaModelo;
import appcortana.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionFacturaVenta extends javax.swing.JFrame {

    conexion con=new conexion();
    Connection cnn=con.conexionbd();

    PreparedStatement ps=null;
    ResultSet rs=null;
    
    public GestionFacturaVenta() {
        initComponents();
        
        cargartabla();
        cargarcombo();
        
    }
    
    public void cargartabla(){
        
        DefaultTableModel tablaa=new DefaultTableModel();
        tablaa.addColumn("NÚMERO FACTURA");
        tablaa.addColumn("FECHA");
        tablaa.addColumn("FORMAPAGO");
        tablaa.addColumn("VALOR TOTAL");
        tablaa.addColumn("DOCUMENTO");
        tablaa.addColumn("NOMBRE");
        tablaa.addColumn("CELULAR");
        
        tablafactura.setModel(tablaa);
        
        String arr[]=new String[10];
        
        try {
            
            ps=cnn.prepareStatement("SELECT * FROM factura_venta");
            rs=ps.executeQuery();
            
            while(rs.next()){
                
                arr[0]=rs.getString(1);
                arr[1]=rs.getString(2);
                arr[2]=rs.getString(3);
                arr[3]=rs.getString(4);
                arr[4]=rs.getString(5);
                arr[5]=rs.getString(6);
                arr[6]=rs.getString(7);
                
                tablaa.addRow(arr);

            }
            
        } 
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Error en la consulta" + ex);
            
        }
        
    }
    
    public void listadatos(){
        
        int lista=tablafactura.getSelectedRow();
        
        if (lista >= 0) {
            
            codigo.setText(tablafactura.getValueAt(lista, 0).toString());
            fecha.setText(tablafactura.getValueAt(lista, 1).toString());
            pago.setSelectedItem(tablafactura.getValueAt(lista, 2).toString());
            valor.setText(tablafactura.getValueAt(lista, 3).toString());
            documento.setSelectedItem(tablafactura.getValueAt(lista, 4).toString());
            nombre.setText(tablafactura.getValueAt(lista, 5).toString());
            celular.setText(tablafactura.getValueAt(lista, 6).toString());
            
        }

    }
    
    public void cargarcombo(){
        
        try {
            
            ps=cnn.prepareStatement("SELECT documentoc FROM cliente");
            rs=ps.executeQuery();  
            
            while (rs.next()){
            
                String aux=rs.getString("documentoc");
                this.documento.addItem(aux);
            
            }
            
        } 
        
        catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Error en cargar el combo"+ ex);
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fecha = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        valor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        nombre = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        celular = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        bguardar = new javax.swing.JButton();
        bmodificar = new javax.swing.JButton();
        beliminar1 = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafactura = new javax.swing.JTable();
        documento = new javax.swing.JComboBox<>();
        pago = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        codigo.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        codigo.setForeground(new java.awt.Color(113, 161, 173));
        codigo.setBorder(null);
        getContentPane().add(codigo);
        codigo.setBounds(240, 250, 320, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(240, 280, 320, 10);

        fecha.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(113, 161, 173));
        fecha.setBorder(null);
        getContentPane().add(fecha);
        fecha.setBounds(240, 350, 320, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(240, 380, 320, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(240, 480, 320, 10);

        valor.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        valor.setForeground(new java.awt.Color(113, 161, 173));
        valor.setBorder(null);
        getContentPane().add(valor);
        valor.setBounds(240, 550, 320, 30);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(240, 580, 320, 10);

        nombre.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(113, 161, 173));
        nombre.setBorder(null);
        getContentPane().add(nombre);
        nombre.setBounds(740, 250, 320, 30);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(740, 280, 320, 10);

        celular.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        celular.setForeground(new java.awt.Color(113, 161, 173));
        celular.setBorder(null);
        getContentPane().add(celular);
        celular.setBounds(740, 350, 320, 30);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(740, 380, 320, 10);

        bguardar.setBackground(new java.awt.Color(255, 255, 255));
        bguardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bguardar.setText("GUARDAR");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bguardar);
        bguardar.setBounds(300, 160, 200, 40);

        bmodificar.setBackground(new java.awt.Color(255, 255, 255));
        bmodificar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bmodificar.setText("MODIFICAR");
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bmodificar);
        bmodificar.setBounds(530, 160, 200, 40);

        beliminar1.setBackground(new java.awt.Color(255, 255, 255));
        beliminar1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        beliminar1.setText("ELIMINAR");
        beliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(beliminar1);
        beliminar1.setBounds(750, 160, 200, 40);

        beliminar.setBackground(new java.awt.Color(255, 255, 255));
        beliminar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        beliminar.setText("Detalle Factura");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        getContentPane().add(beliminar);
        beliminar.setBounds(960, 160, 200, 40);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("CERRAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(1100, -20, 105, 25);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(240, 670, 320, 10);

        tablafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablafactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablafacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablafactura);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 410, 590, 260);

        getContentPane().add(documento);
        documento.setBounds(250, 640, 270, 30);

        pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "T" }));
        getContentPane().add(pago);
        pago.setBounds(240, 450, 290, 30);

        jTextField2.setText("NOMBRE CLIENTE");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(720, 220, 280, 30);

        jTextField1.setText("CELULAR CLIENTE");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(720, 320, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DOCUMENTO_ (10).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed

        GestionDetalleVenta moss= new GestionDetalleVenta();
        moss.setVisible(true);
        moss.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_beliminarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
    
        String c,f,fp,v,d,n,ce;
        int dato;
        
        c=codigo.getText();
        f=fecha.getText();
        fp=(String) pago.getSelectedItem();
        v=valor.getText();
        d=(String) documento.getSelectedItem();
        n=nombre.getText();
        ce=celular.getText();
        
        
        FacturaVenta usu=new FacturaVenta(c, f, fp, v, d, n, ce);
        
        FacturaVentaModelo usubd=new FacturaVentaModelo();
        dato=usubd.insertarfacturav(usu);
        
        if (dato==1) {
            
            JOptionPane.showMessageDialog(null, "Datos guardados");
            cargartabla();
            
        }
        
        else{
            
            JOptionPane.showMessageDialog(null, "Sus datos no fueron guardados");

        }
        
    }//GEN-LAST:event_bguardarActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
    
        String c,f,fp,v,d,n,ce;
        boolean dato;
        
        c=codigo.getText();
        f=fecha.getText();
        fp=(String) pago.getSelectedItem();
        v=valor.getText();
        d=(String) documento.getSelectedItem();
        n=nombre.getText();
        ce=celular.getText();
        
        
        FacturaVenta usu=new FacturaVenta(c, f, fp, v, d, n, ce);
        
        FacturaVentaModelo usubd=new FacturaVentaModelo();
        dato=usubd.modificarusuario(usu);
        
        if (dato==true) {
            
            JOptionPane.showMessageDialog(null, "Datos modificados");
            cargartabla();
            
        }
        
        else{
            
            JOptionPane.showMessageDialog(null, "Sus datos no fueron modificados");

        }
        
    }//GEN-LAST:event_bmodificarActionPerformed

    private void beliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminar1ActionPerformed
    
        String c,f,fp,v,d,n,ce;
        boolean dato;
        
        c=codigo.getText();
        f=fecha.getText();
        fp=(String) pago.getSelectedItem();
        v=valor.getText();
        d=(String) documento.getSelectedItem();
        n=nombre.getText();
        ce=celular.getText();
        
        
        FacturaVenta usu=new FacturaVenta(c, f, fp, v, d, n, ce);
        
        FacturaVentaModelo usubd=new FacturaVentaModelo();
        dato=usubd.eliminarusuario(usu);
        
        if (dato==true) {
            
            JOptionPane.showMessageDialog(null,"Datos eliminados");
            cargartabla();
            
        }
        
        else{
        
            JOptionPane.showMessageDialog(null,"Sus datos no fueron eliminados");
            
        }
        
    }//GEN-LAST:event_beliminar1ActionPerformed

    private void tablafacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablafacturaMouseClicked
    
        listadatos();
        
    }//GEN-LAST:event_tablafacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionFacturaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliminar;
    private javax.swing.JButton beliminar1;
    private javax.swing.JButton bguardar;
    private javax.swing.JButton bmodificar;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> documento;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pago;
    private javax.swing.JTable tablafactura;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
