package Vistas;

import Modelos.ProductoVenta;
import Modelos.ProductoVentaModelo;
import Modelos.Servicio;
import Modelos.ServicioModelo;
import appcortana.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionProductoVenta extends javax.swing.JFrame {

    conexion con=new conexion();
    Connection cnn=con.conexionbd();

    PreparedStatement ps=null;
    ResultSet rs=null;
    
    public GestionProductoVenta() {
        initComponents();
        
        cargartabla();
        cargarcombo();
        
    }
    
    public void cargartabla(){
        
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("NÚMERO DE SERIE");
        tabla.addColumn("DISPONIBILIDAD");
        
        tablaproduc.setModel(tabla);
        
        String arr[]=new String[10];
        
        try {
            
            ps=cnn.prepareStatement("SELECT * FROM productos_venta");
            rs=ps.executeQuery();
            
            while(rs.next()){
                
                arr[0]=rs.getString(1);
                arr[1]=rs.getString(2);
                
                tabla.addRow(arr);

            }
            
        } 
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Error en la consulta" + ex);
            
        }

    }
    
    public void listadatos(){
        
        int lista=tablaproduc.getSelectedRow();
        
        if (lista >= 0) {
            
            serie.setSelectedItem(tablaproduc.getValueAt(lista, 0).toString());
            dispo.setSelectedItem(tablaproduc.getValueAt(lista, 1).toString());
            
        }

    }
    
    public void cargarcombo(){
        
        try {
            
            ps=cnn.prepareStatement("SELECT numserie FROM ingreso");
            rs=ps.executeQuery();  
            
            while (rs.next()){
            
                String aux=rs.getString("numserie");
                this.serie.addItem(aux);
            
            }
            
        } 
        
        catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Error en cargar el combo"+ ex);
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        filtros = new javax.swing.JTextField();
        bguardar = new javax.swing.JButton();
        bmodificar = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        bconsultar1 = new javax.swing.JButton();
        bconsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproduc = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        dispo = new javax.swing.JComboBox<>();
        serie = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(170, 390, 320, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(170, 520, 320, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(620, 230, 290, 30);

        filtros.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        filtros.setForeground(new java.awt.Color(113, 161, 173));
        filtros.setBorder(null);
        getContentPane().add(filtros);
        filtros.setBounds(620, 200, 290, 30);

        bguardar.setBackground(new java.awt.Color(255, 255, 255));
        bguardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bguardar.setText("GUARDAR");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bguardar);
        bguardar.setBounds(150, 630, 200, 60);

        bmodificar.setBackground(new java.awt.Color(255, 255, 255));
        bmodificar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bmodificar.setText("MODIFICAR");
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bmodificar);
        bmodificar.setBounds(410, 630, 200, 60);

        beliminar.setBackground(new java.awt.Color(255, 255, 255));
        beliminar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        beliminar.setText("ELIMINAR");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        getContentPane().add(beliminar);
        beliminar.setBounds(680, 630, 200, 60);

        bconsultar1.setBackground(new java.awt.Color(255, 255, 255));
        bconsultar1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bconsultar1.setText("FILTRAR");
        getContentPane().add(bconsultar1);
        bconsultar1.setBounds(950, 190, 210, 60);

        bconsultar.setBackground(new java.awt.Color(255, 255, 255));
        bconsultar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bconsultar.setText("CONSULTAR");
        getContentPane().add(bconsultar);
        bconsultar.setBounds(950, 630, 210, 60);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaproduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaproduc.setGridColor(new java.awt.Color(79, 127, 133));
        tablaproduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproducMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproduc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 260, 610, 340);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("CERRAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(1100, 0, 105, 25);

        dispo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D", "V" }));
        getContentPane().add(dispo);
        dispo.setBounds(170, 490, 180, 30);

        getContentPane().add(serie);
        serie.setBounds(170, 360, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DOCUMENTO_ (8).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        dispose();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
    
        String n,d;
        int dato;
        
        n=(String) serie.getSelectedItem();
        d=(String) dispo.getSelectedItem();
        
        ProductoVenta usu=new ProductoVenta(n, d);
        
        ProductoVentaModelo usubd=new ProductoVentaModelo();
        dato=usubd.insertarproducto(usu);
        
        if (dato==1) {
            
            JOptionPane.showMessageDialog(null, "Datos guardados");
            cargartabla();
            
        }
        
        else{
            
            JOptionPane.showMessageDialog(null, "Sus datos no fueron guardados");

        }
        
    }//GEN-LAST:event_bguardarActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
    
        String n,d;
        boolean dato;
        
        n=(String) serie.getSelectedItem();
        d=(String) dispo.getSelectedItem();
        
        ProductoVenta usu=new ProductoVenta(n, d);
        
        ProductoVentaModelo usubd=new ProductoVentaModelo();
        dato=usubd.modificarproducto(usu);
        
        if (dato==true) {
            
            JOptionPane.showMessageDialog(null, "Datos modificados");
            cargartabla();
            
        }
        
        else{
            
            JOptionPane.showMessageDialog(null, "Sus datos no fueron modificados");

        }
        
    }//GEN-LAST:event_bmodificarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
    
        String n,d;
        boolean dato;
        
        n=(String) serie.getSelectedItem();
        d=(String) dispo.getSelectedItem();
        
        ProductoVenta usu=new ProductoVenta(n, d);
        
        ProductoVentaModelo usubd=new ProductoVentaModelo();
        dato=usubd.eliminarproducto(usu);
        
        if (dato==true) {
            
            JOptionPane.showMessageDialog(null,"Datos eliminados");
            cargartabla();
            
        }
        
        else{
        
            JOptionPane.showMessageDialog(null,"Sus datos no fueron eliminados");
            
        }
        
    }//GEN-LAST:event_beliminarActionPerformed

    private void tablaproducMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproducMouseClicked
    
        listadatos();
        
    }//GEN-LAST:event_tablaproducMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProductoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProductoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProductoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProductoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProductoVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconsultar;
    private javax.swing.JButton bconsultar1;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bguardar;
    private javax.swing.JButton bmodificar;
    private javax.swing.JComboBox<String> dispo;
    private javax.swing.JTextField filtros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> serie;
    private javax.swing.JTable tablaproduc;
    // End of variables declaration//GEN-END:variables
}
