/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stefania
 */
public class pruebadetalle2 extends javax.swing.JFrame {

    /**
     * Creates new form pruebadetalle2
     */
    public pruebadetalle2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        pago = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        celular1 = new javax.swing.JTextField();
        celular2 = new javax.swing.JTextField();
        celular3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablafactura = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setText("diagnostico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 110, 89, 14);

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        getContentPane().add(fecha);
        fecha.setBounds(110, 40, 210, 30);
        getContentPane().add(pago);
        pago.setBounds(440, 70, 210, 30);
        getContentPane().add(total);
        total.setBounds(110, 70, 210, 30);
        getContentPane().add(codigo);
        codigo.setBounds(110, 10, 210, 30);
        getContentPane().add(documento);
        documento.setBounds(110, 100, 210, 30);
        getContentPane().add(celular);
        celular.setBounds(440, 10, 210, 30);

        jButton2.setText("Guardar Factura Servicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 10, 160, 30);

        jLabel11.setText("Número factura");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 20, 89, 14);

        jLabel12.setText("fecha");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 50, 89, 14);

        jLabel13.setText("forma pago");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 80, 89, 14);
        getContentPane().add(nombre);
        nombre.setBounds(110, 130, 210, 30);

        jLabel14.setText("valor total");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 140, 89, 14);

        jLabel15.setText("descripcion");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 110, 89, 14);

        jLabel16.setText("cedula");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(350, 50, 89, 14);
        getContentPane().add(celular1);
        celular1.setBounds(440, 130, 210, 30);
        getContentPane().add(celular2);
        celular2.setBounds(440, 100, 210, 30);
        getContentPane().add(celular3);
        celular3.setBounds(440, 40, 210, 30);

        jLabel17.setText("documento");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(350, 20, 89, 14);

        jLabel7.setText("ficha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 80, 89, 14);

        jLabel8.setText("cotizacion");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 140, 89, 14);

        tablafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablafactura);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 170, 810, 110);

        tabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetalle);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 470, 640, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebadetalle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebadetalle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebadetalle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebadetalle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebadetalle2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celular;
    private javax.swing.JTextField celular1;
    private javax.swing.JTextField celular2;
    private javax.swing.JTextField celular3;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField documento;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pago;
    private javax.swing.JTable tabladetalle;
    private javax.swing.JTable tablafactura;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
